config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  get "profile", to: "users#profile"
  resources :games do
    get "blackjack", to: "pages#blackjack"
    post "blackjack", to: "pages#blackjack"
    get "poker", to: "pages#poker"
    get "roulette", to: "pages#roulette"
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/game.rb
class Game < ApplicationRecord

  belongs_to :user

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :games, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  def show
    @game = Game.find(params[:id])
  end

  def new
    @game = Game.create!(user: current_user, gold: 1000, name: "New game")
    redirect_to game_path(@game)
  end

end

app/controllers/pages_controller.rb
require 'httparty'

class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [ :home ]

  def home
  end

  def blackjack
    if params["start"].nil?
      @hand = []
    elsif params["start"] == "true" # le joueur démarre la partie de blackjack
      @deck_id = getNewDeck
      @hand= []
      hand = drawCards(@deck_id, 2)
      hand["cards"].each do |card|
        @hand << card["code"]
      end
      @score = scoreCalculation(@hand)
    elsif params["start"] == "stand" # comparaison du score avec la banque
      @deck_id = params[:deck_id]
      @hand = params[:hand]
      @score = scoreCalculation(@hand)
      bank = drawCards(@deck_id, 2)
      raise

    else # le joueur pioche
      card = drawCards(params["deck_id"], 1)
      @deck_id = params[:deck_id]
      @hand = params[:hand]
      @hand << card["cards"][0]["code"]
      @score = scoreCalculation(@hand)
    end
  end

  def roulette
  end

  def poker
  end

  private

  def getNewDeck
    url = "https://deckofcardsapi.com/api/deck/new/shuffle/?deck_count=6"
    response = HTTParty.get(url)
    response.parsed_response["deck_id"]
  end

  def drawCards(deck_id, n)
    url = "https://www.deckofcardsapi.com/api/deck/#{deck_id}/draw/?count=#{n}"
    response = HTTParty.get(url)
    response.parsed_response
  end

  def scoreCalculation(hand)
    score = 0
    hand.each do |card|
      if card[0].match?("A")
        if score > 11
          score += 1
        else
          score += 10
        end
      elsif card[0].match?(/[A-Z]|0/)
        score += 10
      else
        score += card[0].to_i
      end
    end
    if score == 21 && hand.count == 2
      score = "Black Jack !"
    elsif score > 21
      score = "Game over ..."
    end
    return score
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def profile
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/games/show.html.erb
<h1>Partie en cours</h1>
<%= @game.gold %>
<%= link_to "Black Jack", game_blackjack_path(@game), class:"btn btn-success"%>
<%= link_to "Roulette", game_roulette_path(@game), class:"btn btn-success"%>
<%= link_to "Poker Texas hold em", game_poker_path(@game), class:"btn btn-success"%>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Little Casino</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render "shared/navbar" %>
    <%= render "shared/flashes" %>

    <%= yield %>
  </body>
</html>

app/views/pages/blackjack.html.erb
<h1>Welcome to Black Jack !</h1>



<% if @hand.empty? %>
  <%= button_to "Start game", game_blackjack_path, params: {start: true}, method: :post, class:"btn btn-success" %>
<% else %>
  <% @hand.each do |card| %>
    <%= image_tag("https://deckofcardsapi.com/static/img/#{card}.png", width: "100px")  %>
  <% end %>
  <p>Your actual score : <%= @score %></p>
  <% unless @score.is_a?(String) %>
    <%= button_to "Draw", game_blackjack_path, params: {start: false, hand: @hand , deck_id: @deck_id}, method: :post, class:"btn btn-success" %>
    <%= button_to "Stand", game_blackjack_path, params: {start: "stand", hand: @hand , deck_id: @deck_id}, method: :post, class:"btn btn-danger" %>
  <% else  %>
    <%= button_to "Restart game", game_blackjack_path, params: {start: true}, method: :post, class:"btn btn-success" %>
  <% end %>
<% end  %>



<%= link_to "Leave this game", game_path(params[:game_id]), class:"btn btn-success"%>

app/views/pages/home.html.erb
<h1>Welcome to the Little Casino !</h1>
<p>Coucou petite perruche !</p>
  <%= link_to "Play", profile_path, class:"btn btn-success"%>

app/views/pages/poker.html.erb
<h1> Welcome to Poker Texas Hold'em !</h1>
<p> work in progress !</p>

<%= link_to "Leave this game", game_path(params[:game_id]), class:"btn btn-success"%>

app/views/pages/roulette.html.erb
<h1> Welcome to Roulette game !</h1>
<p> work in progress !</p>

<%= link_to "Leave this game", game_path(params[:game_id]), class:"btn btn-success"%>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <div class="container-fluid">
    <%= link_to "#", class: "navbar-brand" do %>
      <%= image_tag "https://raw.githubusercontent.com/lewagon/fullstack-images/master/uikit/logo.png" %>
    <% end %>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
        <% if user_signed_in? %>
          <li class="nav-item active">
            <%= link_to "Home", "#", class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Messages", "#", class: "nav-link" %>
          </li>
          <li class="nav-item dropdown">
            <%= image_tag "https://kitt.lewagon.com/placeholder/users/ssaunier", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { bs_toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
              <%= link_to "Action", "#", class: "dropdown-item" %>
              <%= link_to "Another action", "#", class: "dropdown-item" %>
              <%= link_to "Log out", destroy_user_session_path, data: {turbo_method: :delete}, class: "dropdown-item" %>
            </div>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Login", new_user_session_path, class: "nav-link" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>

app/views/users/profile.html.erb
<h1>Profile page !</h1>

<p>Welcome <%= current_user.email %> !</p>

  <%= link_to "New Game", new_game_path, class:"btn btn-success"%>
  <%= link_to "Load Game", root_path, class:"btn btn-success"%>